server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:10000/auth/realms/workshop
          jwt-set-uri: http://localhost:10000/auth/realms/workshop/protocol/openid-connect/certs
keycloak:
  server-url: http://localhost:10000/auth
front:
  origin: http://localhost:8080
clients:
  user-service:
    base-url: http://localhost:8082
  ticket-service:
    base-url: http://localhost:8083
